import { Form, FormField, FormStep, FormSettings } from '@/types/form';
import { nanoid } from 'nanoid';

const defaultSettings: FormSettings = {
  allowAnonymous: true,
  requireAuth: false,
  emailNotifications: true,
  submitMessage: 'Thank you for your submission!',
};

export const formTemplates: Record<string, Omit<Form, 'id' | 'publicId' | 'createdAt' | 'updatedAt'>> = {
  contact: {
    title: 'Contact Us Form',
    description: "We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
    isPublished: false,
    settings: defaultSettings,
    steps: [
      { id: 1, title: 'Basic Information', order: 1 },
      { id: 2, title: 'Contact Details', order: 2 },
    ],
    fields: [
      {
        id: nanoid(),
        type: 'text',
        label: 'Full Name',
        placeholder: 'Enter your full name',
        helpText: 'Please enter your first and last name',
        required: true,
        stepId: 1,
        order: 1,
      },
      {
        id: nanoid(),
        type: 'email',
        label: 'Email Address',
        placeholder: 'Enter your email address',
        helpText: "We'll use this to contact you back",
        required: true,
        stepId: 1,
        order: 2,
      },
      {
        id: nanoid(),
        type: 'select',
        label: 'Subject',
        placeholder: 'Select a subject',
        required: false,
        stepId: 2,
        order: 3,
        options: [
          { label: 'General Inquiry', value: 'general' },
          { label: 'Support Request', value: 'support' },
          { label: 'Partnership', value: 'partnership' },
          { label: 'Other', value: 'other' },
        ],
      },
      {
        id: nanoid(),
        type: 'textarea',
        label: 'Message',
        placeholder: 'Tell us how we can help you...',
        helpText: 'Minimum 10 characters required',
        required: true,
        stepId: 2,
        order: 4,
        validation: { minLength: 10 },
      },
    ],
  },
  registration: {
    title: 'Registration Form',
    description: 'Create your account to get started with our platform.',
    isPublished: false,
    settings: defaultSettings,
    steps: [
      { id: 1, title: 'Personal Information', order: 1 },
      { id: 2, title: 'Account Details', order: 2 },
    ],
    fields: [
      {
        id: nanoid(),
        type: 'text',
        label: 'First Name',
        placeholder: 'Enter your first name',
        required: true,
        stepId: 1,
        order: 1,
      },
      {
        id: nanoid(),
        type: 'text',
        label: 'Last Name',
        placeholder: 'Enter your last name',
        required: true,
        stepId: 1,
        order: 2,
      },
      {
        id: nanoid(),
        type: 'email',
        label: 'Email Address',
        placeholder: 'Enter your email address',
        required: true,
        stepId: 2,
        order: 3,
      },
      {
        id: nanoid(),
        type: 'phone',
        label: 'Phone Number',
        placeholder: 'Enter your phone number',
        required: false,
        stepId: 2,
        order: 4,
      },
    ],
  },
  survey: {
    title: 'Customer Satisfaction Survey',
    description: 'Help us improve our services by sharing your feedback.',
    isPublished: false,
    settings: defaultSettings,
    steps: [
      { id: 1, title: 'Overall Experience', order: 1 },
    ],
    fields: [
      {
        id: nanoid(),
        type: 'radio',
        label: 'How satisfied are you with our service?',
        required: true,
        stepId: 1,
        order: 1,
        options: [
          { label: 'Very Satisfied', value: '5' },
          { label: 'Satisfied', value: '4' },
          { label: 'Neutral', value: '3' },
          { label: 'Dissatisfied', value: '2' },
          { label: 'Very Dissatisfied', value: '1' },
        ],
      },
      {
        id: nanoid(),
        type: 'checkbox',
        label: 'What features do you use most?',
        required: false,
        stepId: 1,
        order: 2,
        options: [
          { label: 'Dashboard', value: 'dashboard' },
          { label: 'Reports', value: 'reports' },
          { label: 'Settings', value: 'settings' },
          { label: 'Support', value: 'support' },
        ],
      },
      {
        id: nanoid(),
        type: 'textarea',
        label: 'Additional Comments',
        placeholder: 'Please share any additional feedback...',
        required: false,
        stepId: 1,
        order: 3,
      },
    ],
  },
};
